// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoyv5NS6sYSjjS6my9yZ2ukAj9hREVSvg',
    appId: '1:48930304085:web:88721dc4b55a83027ee4dc',
    messagingSenderId: '48930304085',
    projectId: 'whispr-4a6b8',
    authDomain: 'whispr-4a6b8.firebaseapp.com',
    storageBucket: 'whispr-4a6b8.appspot.com',
    measurementId: 'G-SDZCVS1PCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHML_GAJq8cGAEVvyW9FJVRJsaNm76m6w',
    appId: '1:48930304085:android:fff6507c3f2ce9c67ee4dc',
    messagingSenderId: '48930304085',
    projectId: 'whispr-4a6b8',
    storageBucket: 'whispr-4a6b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kAqn8lV1xXYD0Pp2SVo3jLMTXb8r_oA',
    appId: '1:48930304085:ios:2ca9d9c623bfd8987ee4dc',
    messagingSenderId: '48930304085',
    projectId: 'whispr-4a6b8',
    storageBucket: 'whispr-4a6b8.appspot.com',
    iosClientId: '48930304085-va9p1kn974n14sm16ta1hebaph14ddfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4kAqn8lV1xXYD0Pp2SVo3jLMTXb8r_oA',
    appId: '1:48930304085:ios:07fd8d1b6b6141d07ee4dc',
    messagingSenderId: '48930304085',
    projectId: 'whispr-4a6b8',
    storageBucket: 'whispr-4a6b8.appspot.com',
    iosClientId: '48930304085-m6khr572nh668f6b064thf7fjoom3hnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
